services:
  web:
    container_name: laralabo_web
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./app:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  mysql:
    container_name: laralabo_mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql:/mysql
    ports:
      - "3306:3306"
